pipeline {
    agent any

    environment {
        FIREBASE_PROJECT = 'zeiterfassung-ba'
        PATH = "frontend\\src\\npm;$PATH"
       // FIREBASE_TOKEN = credentials('1//03G_TOUmfK_ZPCgYIARAAGAMSNwF-L9IrEg90p9xSiluCoUarLjIHUDEZPxZ_rvMrWOhaaLGUVeqdwo3MvRC0AC4pCpd_Jo5hvJE')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }



        stage('Firebase Deploy') {
            steps {
                script {
                    // Adjust the deploy command based on your project
                    bat "firebase deploy --project ${FIREBASE_PROJECT}"
                }
            }
        }
    }
}
